# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f9c146d124827b74ee43e46ecbd0a5dc4a8887c189131057a4abef46051bf27153f530bdf15c32e82aab170897cacb20ed0c7b002e9a182f1ca3b919e39b16

test:
  secret_key_base: df65082ee8a136ead804a6fb4e6e05e58328dbda20a8680042f16fd7630ba238547d1f1eaf464b385360c5f6d2d78b0f22dd4eb4024ba2b93908f9fd124b77d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
